import Link from "next/link";
import { AiDisclaimer } from "@/components/trust/ai-disclaimer";
import { TrustBadges } from "@/components/trust/trust-badges";
import { buildPageMetadata } from "@/lib/seo/metadata";

export const metadata = buildPageMetadata({
  title: "How AI Interpretation Works",
  description:
    "Transparency about our AI oracle — what it does, what it cannot do, and how to use it wisely.",
  path: "/trust/ai",
});

export default function TrustAiPage() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-12 pb-[max(3rem,env(safe-area-inset-bottom))] sm:px-6 sm:py-16">
      <header className="space-y-3">
        <p className="text-[10px] font-medium uppercase tracking-[0.35em] text-amber-gold">
          Transparency
        </p>
        <h1 className="font-serif text-3xl text-foreground sm:text-4xl">
          How AI interpretation works
        </h1>
        <AiDisclaimer variant="medium" className="text-sm" />
      </header>

      <div className="mt-10 space-y-10 text-base leading-relaxed text-foreground/90">
        <section>
          <h2 className="font-serif text-xl text-foreground">The cast is sacred</h2>
          <p className="mt-3 text-zen-muted">
            Your hexagram is generated by traditional line values (coin method). The
            symbols are not invented by AI — only the language that helps you reflect
            on them.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-foreground">What the AI receives</h2>
          <p className="mt-3 text-zen-muted">
            We send your question, hexagram number, changing lines, and chosen
            interpretation style to our AI provider. We do not sell this data. See our{" "}
            <Link href="/privacy" className="text-amber-gold hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-foreground">Limitations</h2>
          <ul className="mt-3 list-disc space-y-2 pl-5 text-zen-muted">
            <li>AI may generalize or miss cultural nuance</li>
            <li>It cannot know facts about your life it was not told</li>
            <li>It is not therapy, law, medicine, or financial advice</li>
            <li>Outcomes are not guaranteed — the I Ching invites perspective, not fate</li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif text-xl text-foreground">Ethical use</h2>
          <p className="mt-3 text-zen-muted">
            We design prompts to encourage grounded, compassionate guidance. If a
            reading feels harmful or confusing, step away and seek human support.
            Read our full{" "}
            <Link href="/disclaimer" className="text-amber-gold hover:underline">
              disclaimer
            </Link>
            .
          </p>
        </section>
      </div>

      <TrustBadges className="mt-12" />

      <div className="mt-10">
        <Link href="/reading/guided" className="auth-btn-primary text-sm">
          Begin a guided reading
        </Link>
      </div>
    </article>
  );
}
