export type HexagramInfo = {
  number: number;
  nameZh: string;
  nameEn: string;
  summary: string;
};

/** Bottom-to-top binary per King Wen number (index 0 = hexagram 1). */
const HEXAGRAM_BINARIES: string[] = [
  "111111",
  "000000",
  "100010",
  "010001",
  "111010",
  "010111",
  "010000",
  "000010",
  "111011",
  "110111",
  "111000",
  "000111",
  "101111",
  "111101",
  "001000",
  "000100",
  "100110",
  "011001",
  "110000",
  "000011",
  "100101",
  "101001",
  "000001",
  "100000",
  "100111",
  "111001",
  "100001",
  "011110",
  "010010",
  "101101",
  "001110",
  "011100",
  "001111",
  "111100",
  "000101",
  "101000",
  "110101",
  "010100",
  "001010",
  "100011",
  "110001",
  "011000",
  "010110",
  "011101",
  "111110",
  "000110",
  "010000",
  "110110",
  "011011",
  "101110",
  "011101",
  "100100",
  "001001",
  "110100",
  "001011",
  "111010",
  "011110",
  "110001",
  "110011",
  "001011",
  "110100",
  "101011",
  "001010",
  "010101",
];

export function binaryToHexagramNumber(binary: string): number {
  const idx = HEXAGRAM_BINARIES.indexOf(binary);
  if (idx >= 0) return idx + 1;
  return (parseInt(binary, 2) % 64) + 1;
}

export const HEXAGRAMS: HexagramInfo[] = [
  { number: 1, nameZh: "乾", nameEn: "The Creative", summary: "Heaven's vigor — initiate with clarity and persistence." },
  { number: 2, nameZh: "坤", nameEn: "The Receptive", summary: "Earth's devotion — yield, nourish, and carry what is forming." },
  { number: 3, nameZh: "屯", nameEn: "Difficulty at the Beginning", summary: "Sprouting through chaos — patience in early struggle." },
  { number: 4, nameZh: "蒙", nameEn: "Youthful Folly", summary: "The untaught mind — seek a teacher; do not rush." },
  { number: 5, nameZh: "需", nameEn: "Waiting", summary: "Nourishment in delay — prepare while the time ripens." },
  { number: 6, nameZh: "訟", nameEn: "Conflict", summary: "Opposition arises — seek mediation, avoid stubborn battle." },
  { number: 7, nameZh: "師", nameEn: "The Army", summary: "Discipline and order — lead with structure and integrity." },
  { number: 8, nameZh: "比", nameEn: "Holding Together", summary: "Alliance and trust — unite with sincerity." },
  { number: 9, nameZh: "小畜", nameEn: "Small Taming", summary: "Gentle restraint — small accumulations precede release." },
  { number: 10, nameZh: "履", nameEn: "Treading", summary: "Conduct with care — propriety opens the way." },
  { number: 11, nameZh: "泰", nameEn: "Peace", summary: "Heaven and earth unite — flourishing harmony." },
  { number: 12, nameZh: "否", nameEn: "Standstill", summary: "Heaven and earth diverge — withdraw and preserve." },
  { number: 13, nameZh: "同人", nameEn: "Fellowship", summary: "Kindred spirits — openness in the open." },
  { number: 14, nameZh: "大有", nameEn: "Great Possession", summary: "Abundance with virtue — shine without arrogance." },
  { number: 15, nameZh: "謙", nameEn: "Modesty", summary: "Humility succeeds — let merit speak softly." },
  { number: 16, nameZh: "豫", nameEn: "Enthusiasm", summary: "Resonant joy — move others through sincere delight." },
  { number: 17, nameZh: "隨", nameEn: "Following", summary: "Adapt and accompany — follow what is right, not mere whim." },
  { number: 18, nameZh: "蠱", nameEn: "Work on the Decayed", summary: "Repair what has spoiled — courageous renewal." },
  { number: 19, nameZh: "臨", nameEn: "Approach", summary: "Influence draws near — oversee with compassion." },
  { number: 20, nameZh: "觀", nameEn: "Contemplation", summary: "Behold from above — see clearly before acting." },
  { number: 21, nameZh: "噬嗑", nameEn: "Biting Through", summary: "Break the obstacle — justice clears the blockage." },
  { number: 22, nameZh: "賁", nameEn: "Grace", summary: "Beauty and form — adorn without losing substance." },
  { number: 23, nameZh: "剝", nameEn: "Splitting Apart", summary: "Decay at the summit — yield before collapse." },
  { number: 24, nameZh: "復", nameEn: "Return", summary: "The turning point — light returns after darkness." },
  { number: 25, nameZh: "無妄", nameEn: "Innocence", summary: "Act without contrivance — sincerity, not force." },
  { number: 26, nameZh: "大畜", nameEn: "Great Taming", summary: "Store great power — restrain until the moment." },
  { number: 27, nameZh: "頤", nameEn: "Nourishment", summary: "Feed body and word — watch what you take in." },
  { number: 28, nameZh: "大過", nameEn: "Great Exceeding", summary: "The ridgepole bends — extraordinary measures." },
  { number: 29, nameZh: "坎", nameEn: "The Abysmal", summary: "Danger repeated — maintain heart-truth within peril." },
  { number: 30, nameZh: "離", nameEn: "The Clinging", summary: "Fire and clarity — attach to what illumines." },
  { number: 31, nameZh: "咸", nameEn: "Influence", summary: "Mutual attraction — feeling stirs before words." },
  { number: 32, nameZh: "恆", nameEn: "Duration", summary: "Constancy endures — perseverance, not rigidity." },
  { number: 33, nameZh: "遯", nameEn: "Retreat", summary: "Strategic withdrawal — preserve strength." },
  { number: 34, nameZh: "大壯", nameEn: "Great Power", summary: "Strength in motion — use power without recklessness." },
  { number: 35, nameZh: "晉", nameEn: "Progress", summary: "Advance like the sun — recognition through steady rise." },
  { number: 36, nameZh: "明夷", nameEn: "Darkening of the Light", summary: "Hide your radiance — endure in difficult times." },
  { number: 37, nameZh: "家人", nameEn: "The Family", summary: "Inner order — roles and warmth at home." },
  { number: 38, nameZh: "睽", nameEn: "Opposition", summary: "Estrangement — seek small points of agreement." },
  { number: 39, nameZh: "蹇", nameEn: "Obstruction", summary: "The path is blocked — turn inward for counsel." },
  { number: 40, nameZh: "解", nameEn: "Deliverance", summary: "Release from tension — forgive and move on." },
  { number: 41, nameZh: "損", nameEn: "Decrease", summary: "Simplicity and sacrifice — less can be more." },
  { number: 42, nameZh: "益", nameEn: "Increase", summary: "Benefit spreads — give to receive." },
  { number: 43, nameZh: "夬", nameEn: "Breakthrough", summary: "Resolution — announce truth with resolve." },
  { number: 44, nameZh: "姤", nameEn: "Coming to Meet", summary: "Unexpected encounter — beware what arrives unbidden." },
  { number: 45, nameZh: "萃", nameEn: "Gathering", summary: "Assembly — unite around a shared center." },
  { number: 46, nameZh: "升", nameEn: "Pushing Upward", summary: "Gradual ascent — sincerity lifts you." },
  { number: 47, nameZh: "困", nameEn: "Oppression", summary: "Exhaustion — words lose power; endure with grace." },
  { number: 48, nameZh: "井", nameEn: "The Well", summary: "The source endures — return to what nourishes all." },
  { number: 49, nameZh: "革", nameEn: "Revolution", summary: "Radical change — shed the old skin when the time is ripe." },
  { number: 50, nameZh: "鼎", nameEn: "The Cauldron", summary: "Transformation and nourishment — refine the offering." },
  { number: 51, nameZh: "震", nameEn: "The Arousing", summary: "Thunder — shock awakens; maintain composure." },
  { number: 52, nameZh: "艮", nameEn: "Keeping Still", summary: "Mountain stillness — meditate; do not stir rashly." },
  { number: 53, nameZh: "漸", nameEn: "Development", summary: "Gradual growth — like the tree on the slope." },
  { number: 54, nameZh: "歸妹", nameEn: "The Marrying Maiden", summary: "Secondary position — align expectations with reality." },
  { number: 55, nameZh: "豐", nameEn: "Abundance", summary: "Peak fullness — enjoy without clinging." },
  { number: 56, nameZh: "旅", nameEn: "The Wanderer", summary: "Passing through — courtesy and caution abroad." },
  { number: 57, nameZh: "巽", nameEn: "The Gentle", summary: "Wind — penetrate softly, persist gently." },
  { number: 58, nameZh: "兌", nameEn: "The Joyous", summary: "Lake — shared delight, honest exchange." },
  { number: 59, nameZh: "渙", nameEn: "Dispersion", summary: "Dissolve rigidity — reunite what was scattered." },
  { number: 60, nameZh: "節", nameEn: "Limitation", summary: "Measure and boundary — discipline creates freedom." },
  { number: 61, nameZh: "中孚", nameEn: "Inner Truth", summary: "Sincerity of heart — truth moves even pigs and fish." },
  { number: 62, nameZh: "小過", nameEn: "Small Exceeding", summary: "Minor transgression — attend to small matters." },
  { number: 63, nameZh: "既濟", nameEn: "After Completion", summary: "All lines in place — guard against complacency." },
  { number: 64, nameZh: "未濟", nameEn: "Before Completion", summary: "Not yet finished — hope and vigilance." },
];

export function getHexagram(number: number): HexagramInfo {
  return (
    HEXAGRAMS.find((h) => h.number === number) ?? {
      number,
      nameZh: "未知",
      nameEn: "Unknown",
      summary: "The hexagram awaits further study.",
    }
  );
}
